version: "3"
services:
    db:
        build: Dockerfile
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ssafy
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
        ports:
            - 3306:3306
        volumes:
            - ./mysql-init-files/:/docker-entrypoint-initdb.d
        platform: linux/x86_64
